name: Broken Link Checker

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays at midnight
  workflow_dispatch: # Enable manual run

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.html' './**/*.md'
          fail: false